---1

select * from ORDERS 
where ORDER_DATE > '2008-01-14';

---2

select * from OFFICES,SALESREPS
where office = 11 and SALESREPS.NAME ='Sam Clark';

---3

select * from ORDERS
where ORDER_DATE between '2007-12-17' and '2008-01-14';

---4
select * from OFFICES
where OFFICE in (11,12,21);

---5

select * from SALESREPS
where MANAGER is null;

---6
select * from OFFICES
where REGION not like 'West%';

---7

select SALESREPS.NAME,SALESREPS.HIRE_DATE from SALESREPS
order by AGE;

---8

select * from ORDERS
order by QTY asc;

select * from ORDERS
order by AMOUNT desc;

---9

select top 5 * from PRODUCTS 
order by PRICE desc;

---10

select * from (select *,ROW_NUMBER() over (order by Amount desc) as row_num,COUNT(*) over () as total_num
from ORDERS) as sub
where row_num <= Ceiling(0.2 * total_num);

---11

SELECT * FROM ( SELECT *,  ROW_NUMBER() OVER (ORDER BY HIRE_DATE) AS row_num
FROM SALESREPS) AS subquery
WHERE row_num >= 4 AND row_num <= 7;

select * from SALESREPS
where EMPL_NUM between 104 and 107
order by HIRE_DATE;

---12

SELECT DISTINCT MFR_ID, PRODUCT_ID, DESCRIPTION
FROM ORDERS
JOIN PRODUCTS ON ORDERS.MFR = PRODUCTS.MFR_ID AND ORDERS.PRODUCT = PRODUCTS.PRODUCT_ID;

---13

select cust,count(*) as total
from orders
group by cust;

---14

select CUST,SUM(AMOUNT) AS TOTAL
from ORDERS
group by CUST;

---15
select rep,avg(amount) as total_price
from orders
group by rep;

---16

SELECT P.MFR_ID, P.PRODUCT_ID, P.DESCRIPTION, P.PRICE
FROM PRODUCTS P
JOIN (
  SELECT MFR_ID, MAX(PRICE) AS max_price
  FROM PRODUCTS
  GROUP BY MFR_ID
) AS subquery
ON P.MFR_ID = subquery.MFR_ID AND P.PRICE = subquery.max_price;

---17

SELECT
  CUST.CUST_NUM,
  CUST.COMPANY,
  PRODUCTS.DESCRIPTION,
  PRODUCTS.MFR_ID,
  ORDERS.QTY,
  ORDERS.AMOUNT
FROM
  CUSTOMERS CUST
JOIN
  ORDERS
  ON CUST.CUST_NUM = ORDERS.CUST
JOIN
  PRODUCTS
  ON ORDERS.MFR = PRODUCTS.MFR_ID
  AND ORDERS.PRODUCT = PRODUCTS.PRODUCT_ID;

  ---18

  SELECT
  CUST.CUST_NUM,
  CUST.COMPANY,
  ORD.ORDER_NUM,
  ORD.ORDER_DATE
FROM
  CUSTOMERS CUST
LEFT JOIN
  ORDERS ORD
  ON CUST.CUST_NUM = ORD.CUST;

  ---19

  SELECT
  CUST.CUST_NUM,
  CUST.COMPANY
FROM
  CUSTOMERS CUST
WHERE 
  NOT EXISTS (
    SELECT 1
    FROM ORDERS ORD
    WHERE ORD.CUST = CUST.CUST_NUM 
  );

  ---20

  SELECT
  CUST.CUST_NUM,
  CUST.COMPANY
FROM
  CUSTOMERS CUST
JOIN
  ORDERS ORD
  ON CUST.CUST_NUM = ORD.CUST
WHERE
  ORD.ORDER_DATE BETWEEN '2007-12-17' AND '2008-02-15';

  ---21

  SELECT
  PRODUCTS.DESCRIPTION
FROM
  PRODUCTS
JOIN
  ORDERS
  ON PRODUCTS.MFR_ID = ORDERS.MFR
  AND PRODUCTS.PRODUCT_ID = ORDERS.PRODUCT
JOIN
  CUSTOMERS
  ON ORDERS.CUST = CUSTOMERS.CUST_NUM
WHERE
  CUSTOMERS.CREDIT_LIMIT > 40000;

  ---22

 SELECT
  AGE,
  STRING_AGG(NAME, ', ') AS EMPLOYEES
FROM
  SALESREPS
GROUP BY
  AGE
HAVING
  COUNT(*) > 1;

  ---23
 SELECT
  CUST_NUM,
  COMPANY,
  SUM(AMOUNT) AS TOTAL_ORDER_COST
FROM
  CUSTOMERS
JOIN
  ORDERS ON CUSTOMERS.CUST_NUM = ORDERS.CUST
GROUP BY
  CUST_NUM,
  COMPANY
ORDER BY
  TOTAL_ORDER_COST DESC;

  ---24
  SELECT
  ORDER_NUM,
  AMOUNT
FROM
  ORDERS
WHERE
  AMOUNT > (SELECT AVG(AMOUNT) FROM ORDERS);

  ---25

  SELECT
  OFFICE,
  SUM(AMOUNT) AS TOTAL_ORDER_AMOUNT
FROM
  OFFICES
JOIN
  SALESREPS ON OFFICES.OFFICE = SALESREPS.REP_OFFICE
JOIN
  ORDERS ON SALESREPS.EMPL_NUM = ORDERS.REP
GROUP BY
  OFFICE
ORDER BY
  TOTAL_ORDER_AMOUNT DESC;

  ---26

  SELECT
  SR.EMPL_NUM,
  SR.NAME
FROM
  SALESREPS AS SR
INNER JOIN
  SALESREPS AS SUB ON SR.EMPL_NUM = SUB.MANAGER;

  ---27
   SELECT
  SR.EMPL_NUM,
  SR.NAME
FROM
  SALESREPS AS SR
LEFT JOIN
  SALESREPS AS SUB ON SR.EMPL_NUM = SUB.MANAGER
WHERE
  SUB.EMPL_NUM IS NULL;

  ---28

  SELECT
  P.PRODUCT_ID,
  P.DESCRIPTION
FROM
  PRODUCTS AS P
JOIN
  ORDERS AS O ON P.MFR_ID = O.MFR AND P.PRODUCT_ID = O.PRODUCT
JOIN
  SALESREPS AS SR ON O.REP = SR.EMPL_NUM
JOIN
  OFFICES AS OFC ON SR.REP_OFFICE = OFC.OFFICE
WHERE
  OFC.REGION = 'Western';

  ---29

  SELECT
  P.PRODUCT_ID,
  P.DESCRIPTION
FROM
  PRODUCTS AS P
JOIN
  ORDERS AS O ON P.MFR_ID = O.MFR AND P.PRODUCT_ID = O.PRODUCT
JOIN
  CUSTOMERS AS C ON O.CUST = C.CUST_NUM
WHERE
  O.AMOUNT < (
    SELECT AVG(AMOUNT)
    FROM ORDERS
    WHERE CUST = O.CUST
  );	
 
 ---30
 SELECT DISTINCT C.COMPANY
FROM CUSTOMERS AS C
JOIN ORDERS AS O1 ON C.CUST_NUM = O1.CUST
WHERE YEAR(O1.ORDER_DATE) = 2007
  AND C.CUST_NUM NOT IN (
    SELECT O2.CUST
    FROM ORDERS AS O2
    WHERE YEAR(O2.ORDER_DATE) = 2008
  )
GROUP BY C.COMPANY
HAVING COUNT(DISTINCT O1.REP) >= 2;

 
