---Задание 1
SELECT AUDITORIUM, AUDITORIUM_TYPENAME
From AUDITORIUM Inner Join AUDITORIUM_TYPE
On AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE

---Задание 2
SELECT AUDITORIUM, AUDITORIUM_TYPENAME
From AUDITORIUM Inner Join AUDITORIUM_TYPE
On AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE and AUDITORIUM_TYPE.AUDITORIUM_TYPENAME like '%компьютер%'

---Задание 3
SELECT  FACULTY.FACULTY[Факультет], PULPIT.PULPIT[Кафедра], STUDENT.NAME[Имя студента], GROUPS.PROFESSION[Специальность], SUBJECT.SUBJECT[Дисциплина],
		CASE 
		when (PROGRESS.NOTE = 6) then 'шесть'
		when (PROGRESS.NOTE = 7) then 'семь'
		when (PROGRESS.NOTE = 8) then 'восемь'
		else 'другая отметка'
		end [Оценка]
		FROM PROGRESS 
		Inner Join STUDENT ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
		Inner Join GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP
		Inner Join SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT
		Inner Join FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
		Inner Join PULPIT ON SUBJECT.PULPIT = PULPIT.PULPIT
			ORDER BY PROGRESS.NOTE desc, FACULTY.FACULTY asc, PULPIT.PULPIT asc, GROUPS.PROFESSION asc, STUDENT.NAME asc


---Задание 4
SELECT PULPIT.PULPIT_NAME[Кафедра], isnull (TEACHER.TEACHER_NAME, '***')[Преподаватель]
	FROM PULPIT Left Outer Join TEACHER
		ON PULPIT.PULPIT = TEACHER.PULPIT

---Задание 5

SELECT TEACHER.TEACHER, TEACHER.TEACHER_NAME, NULL AS SUBJECT, NULL AS SUBJECT_NAME
FROM TEACHER
LEFT OUTER JOIN SUBJECT ON TEACHER.TEACHER = SUBJECT.PULPIT
WHERE SUBJECT.PULPIT IS NULL;

SELECT NULL AS TEACHER, NULL AS TEACHER_NAME, SUBJECT.SUBJECT AS PULPIT, SUBJECT.SUBJECT_NAME
FROM SUBJECT
LEFT OUTER JOIN TEACHER ON SUBJECT.PULPIT = TEACHER.TEACHER
WHERE TEACHER.TEACHER IS NULL;

SELECT
    TEACHER.TEACHER, TEACHER.TEACHER_NAME, SUBJECT.PULPIT, SUBJECT.SUBJECT_NAME
FROM TEACHER
FULL OUTER JOIN SUBJECT ON TEACHER.TEACHER = SUBJECT.PULPIT
WHERE TEACHER.TEACHER IS NOT NULL OR SUBJECT.PULPIT IS NOT NULL;



---Задание 6
SELECT AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
FROM AUDITORIUM
CROSS JOIN AUDITORIUM_TYPE;




