USE [master]
GO
CREATE DATABASE [Krivenchuk_MyBase]
ON PRIMARY
( NAME = N'Krivenchuk_MyBase', FILENAME = N'M:\Program Files\MSSQL15.SQLEXPRESS01\MSSQL\DATA\Krivenchuk_MyBase.mdf', 
 SIZE = 8192KB,  MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB),


 FILEGROUP [FG_1]
( NAME = 'FG_1',  FILENAME = 'M:\Program Files\MSSQL15.SQLEXPRESS01\MSSQL\DATA\Krivenchuk_MyBase_FG_1.ndf', 
 SIZE = 8192KB, MAXSIZE = UNLIMITED,FILEGROWTH = 65536KB),
( NAME = 'FG_1_2',  FILENAME = N'M:\Program Files\MSSQL15.SQLEXPRESS01\MSSQL\DATA\Krivenchuk_MyBase_FG_1_2.ndf', 
 SIZE = 8192KB, MAXSIZE = UNLIMITED,FILEGROWTH = 65536KB)

LOG ON
(  NAME = N'Krivenchuk_MyBase_log', FILENAME=N'M:\Program Files\MSSQL15.SQLEXPRESS01\MSSQL\DATA\Krivenchuk_MyBase_log.ldf', SIZE = 8192KB, 
MAXSIZE = UNLIMITED,FILEGROWTH = 65536KB)
GO
ALTER DATABASE Krivenchuk_MyBase
 MODIFY FILEGROUP FG_1 DEFAULT;


