---task 1

SELECT
    FACULTY.FACULTY_NAME AS 'Факультет',
    GROUPS.PROFESSION AS 'Специальность',
    PROGRESS.SUBJECT AS 'Дисциплина',
    ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT)), 2) AS 'Средняя оценка'
FROM
    FACULTY
    INNER JOIN GROUPS ON FACULTY.FACULTY = GROUPS.FACULTY
    INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
    INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE
    FACULTY.FACULTY = 'ИДиП'
GROUP BY
    ROLLUP (FACULTY.FACULTY_NAME, GROUPS.PROFESSION, PROGRESS.SUBJECT)
ORDER BY
    FACULTY.FACULTY_NAME, GROUPS.PROFESSION, PROGRESS.SUBJECT;

---task 2

SELECT
    FACULTY.FACULTY_NAME AS 'Факультет',
    GROUPS.PROFESSION AS 'Специальность',
    PROGRESS.SUBJECT AS 'Дисциплина',
    ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT)), 2) AS 'Средняя оценка'
FROM
    FACULTY
    INNER JOIN GROUPS ON FACULTY.FACULTY = GROUPS.FACULTY
    INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
    INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE
    FACULTY.FACULTY = 'ИДиП'
GROUP BY
    CUBE (FACULTY.FACULTY_NAME, GROUPS.PROFESSION, PROGRESS.SUBJECT)
ORDER BY
    FACULTY.FACULTY_NAME, GROUPS.PROFESSION, PROGRESS.SUBJECT;

---task 3

SELECT * FROM (
    -- Запрос для факультета ИДиП
    SELECT
        GROUPS.PROFESSION AS 'Специальность',
        PROGRESS.SUBJECT AS 'Дисциплина',
        ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT)), 2) AS 'Средняя оценка'
    FROM
        GROUPS
        INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
        INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
    WHERE
        GROUPS.FACULTY = 'ИДиП'
    GROUP BY
        GROUPS.PROFESSION, PROGRESS.SUBJECT

    UNION 

    -- Запрос для факультета ХТиТ
    SELECT
        GROUPS.PROFESSION AS 'Специальность',
        PROGRESS.SUBJECT AS 'Дисциплина',
        ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT)), 2) AS 'Средняя оценка'
    FROM
        GROUPS
        INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
        INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
    WHERE
        GROUPS.FACULTY = 'ХТиТ'
    GROUP BY
        GROUPS.PROFESSION, PROGRESS.SUBJECT
) AS CombinedResults;

---task 4 

SELECT
    GROUPS.PROFESSION AS 'Специальность',
    PROGRESS.SUBJECT AS 'Дисциплина',
    ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT)), 2) AS 'Средняя оценка'
FROM
    GROUPS
    INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
    INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE
    GROUPS.FACULTY = 'ИДиП'
GROUP BY
    GROUPS.PROFESSION, PROGRESS.SUBJECT

INTERSECT

SELECT
    GROUPS.PROFESSION AS 'Специальность',
    PROGRESS.SUBJECT AS 'Дисциплина',
    ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT)), 2) AS 'Средняя оценка'
FROM
    GROUPS
    INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
    INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE
    GROUPS.FACULTY = 'ХТиТ'
GROUP BY
    GROUPS.PROFESSION, PROGRESS.SUBJECT;

---task 5


SELECT
    GROUPS.PROFESSION AS 'Специальность',
    PROGRESS.SUBJECT AS 'Дисциплина',
    ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT)), 2) AS 'Средняя оценка'
FROM
    GROUPS
    INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
    INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE
    GROUPS.FACULTY = 'ИДиП'
GROUP BY
    GROUPS.PROFESSION, PROGRESS.SUBJECT

EXCEPT


SELECT
    GROUPS.PROFESSION AS 'Специальность',
    PROGRESS.SUBJECT AS 'Дисциплина',
    ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT)), 2) AS 'Средняя оценка'
FROM
    GROUPS
    INNER JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
    INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE
    GROUPS.FACULTY = 'ХТиТ'
GROUP BY
    GROUPS.PROFESSION, PROGRESS.SUBJECT;



